#index:
#    path: /
#    controller: App\Controller\DefaultController::index

first_route:
  path: /first-route
  controller: App\Controller\MagicController::firstRoute

first_twig:
  path: /first-twig
  controller: App\Controller\MagicController::firstTwig